[project]
name = "ai-lab-project"
version = "0.1.0"
requires-python = ">3.12,<3.13"
dependencies = [
    "ipykernel>=6.30.0",
    "mediapipe>=0.10.21",
    "numpy>=1.26.4",
    "pedalboard>=0.9.17",
    "pip>=25.1.1",
    "scikit-learn>=1.7.1",
    "sounddevice>=0.5.2",
    "soundfile>=0.13.1",
]
